name: Publish Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'latest'
        type: choice
        options:
        - latest
        - next

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [18.12.1]
        os: [ubuntu-latest]
        pnpm: [8.5.1]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      - name: Setup Node.js (${{ matrix.node }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - run: |
          echo "Release Tag: $TAG"
        env:
          TAG: ${{ inputs.tag }}

      # - run: pnpm publish --tag latest
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
